version: '3.8'
services:
  dante-server:
    container_name: dante-container
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 1080:1080
    volumes:
      - ./sockd.conf:/sockd.conf